export interface SupportedLanguages {
  created_at: string, 
  deleted_at: string,
  enabled: boolean,
  id: number,
  iso_language: string,
  is_default: boolean,
  language_name: string,
  language_blob: string,
  name: string,
  out_of_date: string,
  shop_id: number,
  shop_language_id: string,
  source: any,
  updated_at: string, 
};